title: About Bryan
author: Bryan Lee
email: bclee@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website. I hope you learn a little about me here.

# social links
twitter_username: bryanlee # DO NOT include the @ character, or else the build will fail!
github_username:  encryptedthumb # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
